In [1]:
import sys
from pathlib import Path

class ImportMyModules:

    def __init__(self) -> None:
        self.cwd = Path.cwd().resolve()

    def _get_repo_root(self, folder: str) -> Path:
        return next(
            parent for parent in [self.cwd, *self.cwd.parents]
            if (parent / "lib" / "peregrin" / folder).exists()
        )

    def insert_path(self, folder: str) -> None:
        repo_root = self._get_repo_root("src")

        package_root = repo_root / "lib" / "peregrin"
        print(f"Adding {package_root} to sys.path")
        sys.path.insert(0, str(package_root))

importer = ImportMyModules()
importer.insert_path("src")
importer.insert_path("data")

from importlib import reload

Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path
Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path

In [2]:
import src.data_handler.data_loader as load_module
reload(load_module)
load_data = load_module.load_data

data = load_data(r"./dummy_data/single/dummy_cell_tracks.csv", {'id': 'track_id', 'x': 'x_coordinate', 'y': 'y_coordinate', 't': 'time_point'}, spatial_unit="micrometer", time_unit="minute")

In [3]:
data.metadata.get()

{'timeunits': 'min',
 'spatialunits': 'μm',
 'nframes': 100,
 'timeinterval': 1.0,
 'columns': ['set',
  'subset',
  'track_id',
  'time_point',
  'x_coordinate',
  'y_coordinate',
  'track_uid']}

In [4]:
import src.data_compute.object_interface as object_module
reload(object_module)
create_object = object_module.create_object

In [5]:
import src.data_compute.data_frames as data_frames_module
reload(data_frames_module)
calculate = data_frames_module.calc

In [6]:
create_object

In [7]:
data.metadata.get()

{'timeunits': 'min',
 'spatialunits': 'μm',
 'nframes': 100,
 'timeinterval': 1.0,
 'columns': ['set',
  'subset',
  'track_id',
  'time_point',
  'x_coordinate',
  'y_coordinate',
  'track_uid']}

In [8]:
my_object = create_object(data)
print(my_object.metadata)
print(my_object.metadata['spatialunits'])

{'timeunits': 'min', 'spatialunits': 'μm', 'nframes': 100, 'timeinterval': 1.0}
μm

In [9]:
my_object.compute_spots()

shape: (2_397, 21)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ track_id ┆ time_poin ┆ x_coordin ┆ y_coordin ┆ … ┆ cum_mean_ ┆ cum_mean_ ┆ cum_direc ┆ cum_direc │
│ ---      ┆ t         ┆ ate       ┆ ate       ┆   ┆ direction ┆ direction ┆ tion_mean ┆ tion_var  │
│ f64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ al_change ┆ al_change ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ _ra…      ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0      ┆ 3.0       ┆ 137.51414 ┆ 236.60029 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 9         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 4.0       ┆ 139.12744 ┆ 237.66194 ┆ … ┆ null      ┆ null      ┆ 0.582021  ┆ 0.0       │
│          ┆           ┆ 7         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 5.0       ┆ 140.35646 ┆ 240.40668 ┆ … ┆ 32.531211 ┆ 10.843737 ┆ 0.86591   ┆ 0.040026  │
│          ┆           ┆ 3         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 6.0       ┆ 140.90310 ┆ 242.20398 ┆ … ┆ 19.867765 ┆ 4.966941  ┆ 1.005371  ┆ 0.044989  │
│          ┆           ┆ 9         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 7.0       ┆ 143.09024 ┆ 243.67619 ┆ … ┆ 26.290972 ┆ 5.258194  ┆ 0.899637  ┆ 0.049444  │
│          ┆           ┆ 2         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 24.0     ┆ 95.0      ┆ -3.017567 ┆ 285.43198 ┆ … ┆ 26.430625 ┆ 0.275319  ┆ -3.085176 ┆ 0.536443  │
│          ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 24.0     ┆ 96.0      ┆ -5.199282 ┆ 285.07013 ┆ … ┆ 26.576431 ┆ 0.273984  ┆ -3.082784 ┆ 0.530914  │
│          ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ 24.0     ┆ 97.0      ┆ -7.089226 ┆ 285.75360 ┆ … ┆ 26.604793 ┆ 0.271477  ┆ -3.091375 ┆ 0.526261  │
│          ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ 24.0     ┆ 98.0      ┆ -10.93673 ┆ 287.96004 ┆ … ┆ 26.433104 ┆ 0.267001  ┆ -3.102923 ┆ 0.522477  │
│          ┆           ┆ 1         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 24.0     ┆ 99.0      ┆ -12.18935 ┆ 290.10379 ┆ … ┆ 26.46816  ┆ 0.264682  ┆ -3.121586 ┆ 0.522462  │
│          ┆           ┆ 7         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
my_object.metadata

{'timeunits': 'min', 'spatialunits': 'μm', 'nframes': 100, 'timeinterval': 1.0}

In [11]:
calculate.metadata

{'timeunits': 'min', 'spatialunits': 'μm', 'nframes': 100, 'timeinterval': 1.0}

In [12]:
my_object.compute_tracks()

shape: (24, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ set       ┆ track_uid ┆ speed_min ┆ speed_max ┆ … ┆ track_poi ┆ track_dis ┆ straightn ┆ track_id │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ nts       ┆ placement ┆ ess_ratio ┆ ---      │
│ str       ┆ i64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ u32       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ dummy_cel ┆ 0         ┆ 1.233776  ┆ 4.252455  ┆ … ┆ 97        ┆ 45.890725 ┆ 0.178304  ┆ 1.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 1         ┆ 2.171651  ┆ 7.239426  ┆ … ┆ 100       ┆ 332.38460 ┆ 0.765065  ┆ 2.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 2         ┆ 3.902545  ┆ 11.37175  ┆ … ┆ 100       ┆ 726.93059 ┆ 0.962163  ┆ 3.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 3         ┆ 0.936632  ┆ 3.706162  ┆ … ┆ 100       ┆ 200.03805 ┆ 0.868102  ┆ 4.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 4         ┆ 3.280677  ┆ 10.68337  ┆ … ┆ 100       ┆ 281.34948 ┆ 0.426164  ┆ 5.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ dummy_cel ┆ 19        ┆ 1.709629  ┆ 8.499498  ┆ … ┆ 100       ┆ 461.85673 ┆ 0.870815  ┆ 20.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 20        ┆ 1.919261  ┆ 8.121097  ┆ … ┆ 100       ┆ 482.80912 ┆ 0.928928  ┆ 21.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 21        ┆ 1.201748  ┆ 5.099428  ┆ … ┆ 100       ┆ 217.29065 ┆ 0.764885  ┆ 22.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 22        ┆ 2.057317  ┆ 9.395883  ┆ … ┆ 100       ┆ 93.600505 ┆ 0.158337  ┆ 23.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 23        ┆ 0.86279   ┆ 4.435272  ┆ … ┆ 100       ┆ 115.42665 ┆ 0.47392   ┆ 24.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘