In [23]:
import sys
from pathlib import Path

class ImportMyModules:

    def __init__(self) -> None:
        self.cwd = Path.cwd().resolve()

    def _get_repo_root(self, folder: str) -> Path:
        return next(
            parent for parent in [self.cwd, *self.cwd.parents]
            if (parent / "lib" / "peregrin" / folder).exists()
        )

    def insert_path(self, folder: str) -> None:
        repo_root = self._get_repo_root("src")

        package_root = repo_root / "lib" / "peregrin"
        print(f"Adding {package_root} to sys.path")
        sys.path.insert(0, str(package_root))

importer = ImportMyModules()
importer.insert_path("src")
importer.insert_path("data")

from importlib import reload

Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path
Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path

In [24]:
import src.loader.load as load_module
reload(load_module)
load_data = load_module.load_data

In [25]:
data = load_data(r"./dummy_cell_tracks.csv", {'id': 'track_id', 'x': 'x_coordinate', 'y': 'y_coordinate', 't': 'time_point'}, spatial_unit="micrometer", time_unit="second")

In [30]:
import src.compute.stats as stats_module
reload(stats_module)
stats = stats_module.stats

In [33]:
spots = stats.spots(data)
spots

shape: (1_710, 21)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ track_id ┆ time_poin ┆ x_coordin ┆ y_coordin ┆ … ┆ cum_mean_ ┆ cum_mean_ ┆ cum_direc ┆ cum_direc │
│ ---      ┆ t         ┆ ate       ┆ ate       ┆   ┆ direction ┆ direction ┆ tion_mean ┆ tion_var  │
│ f64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ al_change ┆ al_change ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ _ra…      ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0      ┆ 25.0      ┆ 242.8987  ┆ 57.809882 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1.0      ┆ 26.0      ┆ 245.22802 ┆ 54.597547 ┆ … ┆ null      ┆ null      ┆ -0.943409 ┆ 0.0       │
│          ┆           ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 27.0      ┆ 249.82726 ┆ 49.532794 ┆ … ┆ 6.295573  ┆ 2.098524  ┆ -0.88847  ┆ 0.001509  │
│          ┆           ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 28.0      ┆ 252.71536 ┆ 45.316116 ┆ … ┆ 7.064818  ┆ 1.766204  ┆ -0.915755 ┆ 0.001749  │
│          ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 29.0      ┆ 253.58543 ┆ 39.076147 ┆ … ┆ 13.533307 ┆ 2.706661  ┆ -1.042861 ┆ 0.026066  │
│          ┆           ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 24.0     ┆ 95.0      ┆ 165.66373 ┆ 651.14549 ┆ … ┆ 9.380266  ┆ 0.12676   ┆ 1.639609  ┆ 0.072347  │
│          ┆           ┆ 8         ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 24.0     ┆ 96.0      ┆ 160.94707 ┆ 653.76238 ┆ … ┆ 9.301542  ┆ 0.124021  ┆ 1.651899  ┆ 0.07746   │
│          ┆           ┆ 4         ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 24.0     ┆ 97.0      ┆ 151.21469 ┆ 656.33639 ┆ … ┆ 9.367845  ┆ 0.123261  ┆ 1.665642  ┆ 0.085232  │
│          ┆           ┆ 4         ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ 24.0     ┆ 98.0      ┆ 146.93661 ┆ 659.48051 ┆ … ┆ 9.529596  ┆ 0.123761  ┆ 1.676412  ┆ 0.088454  │
│          ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 24.0     ┆ 99.0      ┆ 143.78916 ┆ 661.13852 ┆ … ┆ 9.516499  ┆ 0.122006  ┆ 1.688306  ┆ 0.092998  │
│          ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [38]:
tracks = stats.tracks(spots)
tracks

shape: (24, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ set       ┆ track_uid ┆ speed_min ┆ speed_max ┆ … ┆ track_poi ┆ track_dis ┆ straightn ┆ track_id │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ nts       ┆ placement ┆ ess_ratio ┆ ---      │
│ str       ┆ i64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ u32       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ dummy_cel ┆ 0         ┆ 1.887846  ┆ 7.510075  ┆ … ┆ 61        ┆ 45.148695 ┆ 0.148057  ┆ 1.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 1         ┆ 0.630499  ┆ 4.222559  ┆ … ┆ 71        ┆ 76.232016 ┆ 0.47692   ┆ 2.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 2         ┆ 1.759553  ┆ 6.590044  ┆ … ┆ 52        ┆ 94.385655 ┆ 0.421276  ┆ 3.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 3         ┆ 0.450875  ┆ 3.833588  ┆ … ┆ 78        ┆ 67.115054 ┆ 0.400005  ┆ 4.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 4         ┆ 0.43936   ┆ 3.481555  ┆ … ┆ 96        ┆ 61.080718 ┆ 0.306576  ┆ 5.0      │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ dummy_cel ┆ 19        ┆ 1.816875  ┆ 5.021864  ┆ … ┆ 66        ┆ 154.79507 ┆ 0.664828  ┆ 20.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 20        ┆ 2.494322  ┆ 7.844056  ┆ … ┆ 53        ┆ 75.658984 ┆ 0.290282  ┆ 21.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 21        ┆ 3.623673  ┆ 11.663155 ┆ … ┆ 86        ┆ 97.410005 ┆ 0.151038  ┆ 22.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 22        ┆ 4.29935   ┆ 10.441416 ┆ … ┆ 61        ┆ 213.90558 ┆ 0.468022  ┆ 23.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ dummy_cel ┆ 23        ┆ 3.557446  ┆ 10.067014 ┆ … ┆ 78        ┆ 445.22232 ┆ 0.906888  ┆ 24.0     │
│ l_tracks. ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ csv       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [39]:
frames = stats.frames(spots)
frames

shape: (1_188, 53)
┌────────────┬────────────┬───────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ set        ┆ time_point ┆ frame ┆ cum_track_ ┆ … ┆ instantan ┆ cum_direc ┆ cum_direc ┆ grouping_ │
│ ---        ┆ ---        ┆ ---   ┆ length_min ┆   ┆ eous_dire ┆ tion_mean ┆ tion_var  ┆ level     │
│ str        ┆ f64        ┆ i64   ┆ ---        ┆   ┆ ction_var ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆       ┆ f64        ┆   ┆ ---       ┆ f64       ┆ f64       ┆ str       │
│            ┆            ┆       ┆            ┆   ┆ f64       ┆           ┆           ┆           │
╞════════════╪════════════╪═══════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ dummy_cell ┆ 25.0       ┆ 0     ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ dummy_cell ┆ 26.0       ┆ 1     ┆ 3.96798    ┆ … ┆ 0.0       ┆ -0.943409 ┆ 0.0       ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ dummy_cell ┆ 27.0       ┆ 2     ┆ 10.809378  ┆ … ┆ 0.0       ┆ -0.88847  ┆ 0.0       ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ dummy_cell ┆ 28.0       ┆ 3     ┆ 15.920296  ┆ … ┆ 0.0       ┆ -0.915755 ┆ 0.0       ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ dummy_cell ┆ 29.0       ┆ 4     ┆ 22.220632  ┆ … ┆ 0.0       ┆ -1.042861 ┆ 0.0       ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …     ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ dummy_cell ┆ 75.0       ┆ 56    ┆ 423.231731 ┆ … ┆ 0.0       ┆ -2.794654 ┆ 0.0       ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ dummy_cell ┆ 76.0       ┆ 57    ┆ 431.486085 ┆ … ┆ 1.1102e-1 ┆ -2.765795 ┆ 1.1102e-1 ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆ 6         ┆           ┆ 6         ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ dummy_cell ┆ 77.0       ┆ 58    ┆ 440.191349 ┆ … ┆ 0.0       ┆ -2.749326 ┆ 1.1102e-1 ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆           ┆           ┆ 6         ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ dummy_cell ┆ 78.0       ┆ 59    ┆ 447.30516  ┆ … ┆ 0.0       ┆ -2.748249 ┆ 0.0       ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ dummy_cell ┆ 79.0       ┆ 60    ┆ 457.041418 ┆ … ┆ 0.0       ┆ -2.725372 ┆ 0.0       ┆ set       │
│ _tracks.cs ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ v          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴───────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [43]:
import src.compute.stats as stats_module
reload(stats_module)
Calc = stats_module.Calc

tlags = Calc(bootstrap_ci=True).time_intervals(spots)
tlags

shape: (95, 10)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ set       ┆ frame_lag ┆ time_lag ┆ MSD       ┆ … ┆ position_ ┆ direction ┆ direction ┆ grouping_ │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ pairs_con ┆ al_change ┆ al_change ┆ level     │
│ str       ┆ i64       ┆ f64      ┆ f64       ┆   ┆ tributing ┆ _mean     ┆ _var      ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│           ┆           ┆          ┆           ┆   ┆ i64       ┆ f64       ┆ f64       ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ dummy_cel ┆ 1         ┆ 1.0      ┆ 26.073176 ┆ … ┆ 1686      ┆ 0.577473  ┆ 0.113232  ┆ set       │
│ l_tracks. ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ dummy_cel ┆ 2         ┆ 2.0      ┆ 97.159923 ┆ … ┆ 1662      ┆ 0.980407  ┆ 0.180693  ┆ set       │
│ l_tracks. ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ dummy_cel ┆ 3         ┆ 3.0      ┆ 210.16805 ┆ … ┆ 1638      ┆ 1.144023  ┆ 0.238074  ┆ set       │
│ l_tracks. ┆           ┆          ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ dummy_cel ┆ 4         ┆ 4.0      ┆ 361.90286 ┆ … ┆ 1614      ┆ 1.653601  ┆ 0.295138  ┆ set       │
│ l_tracks. ┆           ┆          ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ dummy_cel ┆ 5         ┆ 5.0      ┆ 549.14315 ┆ … ┆ 1590      ┆ 2.151886  ┆ 0.344206  ┆ set       │
│ l_tracks. ┆           ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ dummy_cel ┆ 91        ┆ 91.0     ┆ 3752.7172 ┆ … ┆ 5         ┆ 140.15957 ┆ 0.746169  ┆ set       │
│ l_tracks. ┆           ┆          ┆ 63        ┆   ┆           ┆ 6         ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ dummy_cel ┆ 92        ┆ 92.0     ┆ 3732.5165 ┆ … ┆ 4         ┆ 143.95745 ┆ 0.155161  ┆ set       │
│ l_tracks. ┆           ┆          ┆ 94        ┆   ┆           ┆ 7         ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ dummy_cel ┆ 93        ┆ 93.0     ┆ 3728.1462 ┆ … ┆ 3         ┆ 147.35869 ┆ 0.005232  ┆ set       │
│ l_tracks. ┆           ┆          ┆ 41        ┆   ┆           ┆           ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ dummy_cel ┆ 94        ┆ 94.0     ┆ 3744.2731 ┆ … ┆ 2         ┆ 147.22615 ┆ 0.0       ┆ set       │
│ l_tracks. ┆           ┆          ┆ 83        ┆   ┆           ┆ 5         ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ dummy_cel ┆ 95        ┆ 95.0     ┆ 3730.8540 ┆ … ┆ 1         ┆ null      ┆ null      ┆ set       │
│ l_tracks. ┆           ┆          ┆ 64        ┆   ┆           ┆           ┆           ┆           │
│ csv       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘