In [1]:
import sys
from pathlib import Path

class ImportMyModules:

    def __init__(self) -> None:
        self.cwd = Path.cwd().resolve()

    def _get_repo_root(self, folder: str) -> Path:
        return next(
            parent for parent in [self.cwd, *self.cwd.parents]
            if (parent / "lib" / "peregrin" / folder).exists()
        )

    def insert_path(self, folder: str) -> None:
        repo_root = self._get_repo_root("src")

        package_root = repo_root / "lib" / "peregrin"
        print(f"Adding {package_root} to sys.path")
        sys.path.insert(0, str(package_root))

importer = ImportMyModules()
importer.insert_path("src")
importer.insert_path("data")

from importlib import reload

Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path
Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path

In [2]:
import src.data_handler.data_loader as load_module
reload(load_module)
load_data = load_module.load_data

In [3]:
# data = load_data(r"./dummy_data/testing_0")

data = load_data(
    r"./dummy_data/tree",
    colnames = {
        'id': 'track_id',
        't': 'time_point',
        'x': 'x_coordinate',
        'y': 'y_coordinate'
    },
)

C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin\src\data_handler\df_metadata_manager.py:176: InputWarning: No time units found in input files.
 Please specify the time units using <load_data result>.metadata.write(time_unit="<unit>")
  self._check()
C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin\src\data_handler\df_metadata_manager.py:176: InputWarning: No spatial units found in input files.
 Please specify the spatial units using <load_data result>.metadata.write(spatial_unit="<unit>")
  self._check()

In [4]:
data.metadata.write(spatialunits='um', timeunits='s')
data.metadata.get()

{'timeunits': 's',
 'spatialunits': 'μm',
 'nframes': 97,
 'timeinterval': 1.0,
 'columns': ['track_id',
  'time_point',
  'x_coordinate',
  'y_coordinate',
  'track_uid']}

In [5]:
data

shape: (4_656, 9)
┌──────────┬────────────┬────────────┬────────────┬───┬──────────┬─────────┬──────────┬────────────┐
│ track_id ┆ time_point ┆ x_coordina ┆ y_coordina ┆ … ┆ subset   ┆ group   ┆ subgroup ┆ subsubgrou │
│ ---      ┆ ---        ┆ te         ┆ te         ┆   ┆ ---      ┆ ---     ┆ ---      ┆ p          │
│ f64      ┆ f64        ┆ ---        ┆ ---        ┆   ┆ str      ┆ str     ┆ str      ┆ ---        │
│          ┆            ┆ f64        ┆ f64        ┆   ┆          ┆         ┆          ┆ str        │
╞══════════╪════════════╪════════════╪════════════╪═══╪══════════╪═════════╪══════════╪════════════╡
│ 1.0      ┆ 3.0        ┆ 398.279126 ┆ 240.018418 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 1.0      ┆ 4.0        ┆ 403.759745 ┆ 246.280817 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 1.0      ┆ 5.0        ┆ 410.293969 ┆ 252.025005 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 1.0      ┆ 6.0        ┆ 417.515554 ┆ 255.846523 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 1.0      ┆ 7.0        ┆ 425.567799 ┆ 261.606225 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ …        ┆ …          ┆ …          ┆ …          ┆ … ┆ …        ┆ …       ┆ …        ┆ …          │
│ 48.0     ┆ 95.0       ┆ -263.10974 ┆ 558.308107 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 7          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 48.0     ┆ 96.0       ┆ -263.49867 ┆ 563.497103 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 3          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 48.0     ┆ 97.0       ┆ -261.75510 ┆ 566.663271 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 1          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 48.0     ┆ 98.0       ┆ -260.39627 ┆ 571.391335 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 5          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 48.0     ┆ 99.0       ┆ -257.26308 ┆ 576.229309 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 5          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
└──────────┴────────────┴────────────┴────────────┴───┴──────────┴─────────┴──────────┴────────────┘

In [6]:
import src.object_interface as object_module
reload(object_module)
create_object = object_module.create_object

In [7]:
data_object = create_object(data)

In [ ]:
spots_df = data_object.compute_spots(data, enrich=True)
print(len(spots_df['track_uid'].unique()), " unique tracks")
spots_df

48  unique tracks

shape: (4_656, 13)
┌──────────┬────────────┬─────────────┬─────────────┬───┬───────────┬───────┬──────────┬───────────┐
│ track_id ┆ time_point ┆ x_coordinat ┆ y_coordinat ┆ … ┆ track_uid ┆ frame ┆ distance ┆ direction │
│ ---      ┆ ---        ┆ e           ┆ e           ┆   ┆ ---       ┆ ---   ┆ ---      ┆ ---       │
│ f64      ┆ f64        ┆ ---         ┆ ---         ┆   ┆ i64       ┆ i64   ┆ f64      ┆ f64       │
│          ┆            ┆ f64         ┆ f64         ┆   ┆           ┆       ┆          ┆           │
╞══════════╪════════════╪═════════════╪═════════════╪═══╪═══════════╪═══════╪══════════╪═══════════╡
│ 1.0      ┆ 3.0        ┆ 398.279126  ┆ 240.018418  ┆ … ┆ 1         ┆ 0     ┆ null     ┆ null      │
│ 1.0      ┆ 4.0        ┆ 403.759745  ┆ 246.280817  ┆ … ┆ 1         ┆ 1     ┆ 8.321949 ┆ 0.851874  │
│ 1.0      ┆ 5.0        ┆ 410.293969  ┆ 252.025005  ┆ … ┆ 1         ┆ 2     ┆ 8.700102 ┆ 0.721143  │
│ 1.0      ┆ 6.0        ┆ 417.515554  ┆ 255.846523  ┆ … ┆ 1         ┆ 3     ┆ 8.170391 ┆ 0.486718  │
│ 1.0      ┆ 7.0        ┆ 425.567799  ┆ 261.606225  ┆ … ┆ 1         ┆ 4     ┆ 9.900142 ┆ 0.620915  │
│ …        ┆ …          ┆ …           ┆ …           ┆ … ┆ …         ┆ …     ┆ …        ┆ …         │
│ 48.0     ┆ 95.0       ┆ -263.109747 ┆ 558.308107  ┆ … ┆ 48        ┆ 92    ┆ 5.402618 ┆ 1.925386  │
│ 48.0     ┆ 96.0       ┆ -263.498673 ┆ 563.497103  ┆ … ┆ 48        ┆ 93    ┆ 5.203551 ┆ 1.645608  │
│ 48.0     ┆ 97.0       ┆ -261.755101 ┆ 566.663271  ┆ … ┆ 48        ┆ 94    ┆ 3.614507 ┆ 1.067425  │
│ 48.0     ┆ 98.0       ┆ -260.396275 ┆ 571.391335  ┆ … ┆ 48        ┆ 95    ┆ 4.919451 ┆ 1.290943  │
│ 48.0     ┆ 99.0       ┆ -257.263085 ┆ 576.229309  ┆ … ┆ 48        ┆ 96    ┆ 5.763928 ┆ 0.996093  │
└──────────┴────────────┴─────────────┴─────────────┴───┴───────────┴───────┴──────────┴───────────┘

In [9]:
import src.data_compute.data_frames as frames_module
reload(frames_module)
calcs = frames_module.calc

In [10]:
calcs._enrich_spots(spots_df, t_step= 1.0)

shape: (4_656, 25)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ track_id ┆ time_poin ┆ x_coordin ┆ y_coordin ┆ … ┆ cum_mean_ ┆ cum_mean_ ┆ cum_direc ┆ cum_direc │
│ ---      ┆ t         ┆ ate       ┆ ate       ┆   ┆ direction ┆ direction ┆ tion_mean ┆ tion_var  │
│ f64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ al_change ┆ al_change ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ _ra…      ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0      ┆ 3.0       ┆ 398.27912 ┆ 240.01841 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 6         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 4.0       ┆ 403.75974 ┆ 246.28081 ┆ … ┆ null      ┆ null      ┆ 0.851874  ┆ 0.0       │
│          ┆           ┆ 5         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 5.0       ┆ 410.29396 ┆ 252.02500 ┆ … ┆ 7.490328  ┆ 2.496776  ┆ 0.786509  ┆ 0.002136  │
│          ┆           ┆ 9         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 6.0       ┆ 417.51555 ┆ 255.84652 ┆ … ┆ 10.46095  ┆ 2.615237  ┆ 0.68677   ┆ 0.011378  │
│          ┆           ┆ 4         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 7.0       ┆ 425.56779 ┆ 261.60622 ┆ … ┆ 9.536941  ┆ 1.907388  ┆ 0.670169  ┆ 0.008939  │
│          ┆           ┆ 9         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 48.0     ┆ 95.0      ┆ -263.1097 ┆ 558.30810 ┆ … ┆ 12.019773 ┆ 0.129245  ┆ 2.751283  ┆ 0.256409  │
│          ┆           ┆ 47        ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 96.0      ┆ -263.4986 ┆ 563.49710 ┆ … ┆ 12.063364 ┆ 0.128334  ┆ 2.738304  ┆ 0.259519  │
│          ┆           ┆ 73        ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 97.0      ┆ -261.7551 ┆ 566.66327 ┆ … ┆ 12.28986  ┆ 0.129367  ┆ 2.723836  ┆ 0.268383  │
│          ┆           ┆ 01        ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 98.0      ┆ -260.3962 ┆ 571.39133 ┆ … ┆ 12.295357 ┆ 0.128077  ┆ 2.709462  ┆ 0.274562  │
│          ┆           ┆ 75        ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 99.0      ┆ -257.2630 ┆ 576.22930 ┆ … ┆ 12.343761 ┆ 0.127255  ┆ 2.695071  ┆ 0.283525  │
│          ┆           ┆ 85        ┆ 9         ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
tracks = data_object.compute_tracks()
tracks

shape: (48, 28)
┌────────────┬──────────┬─────────┬──────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ subsubgrou ┆ subgroup ┆ group   ┆ subset   ┆ … ┆ speed_medi ┆ greatest_d ┆ direction ┆ straightn │
│ p          ┆ ---      ┆ ---     ┆ ---      ┆   ┆ an         ┆ istance    ┆ ality     ┆ ess       │
│ ---        ┆ str      ┆ str     ┆ str      ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆          ┆         ┆          ┆   ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪══════════╪═════════╪══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ dummy_cell ┆ rep1     ┆ ctrl    ┆ subset_1 ┆ … ┆ 7.24023    ┆ 635.975121 ┆ 0.930173  ┆ 0.930173  │
│ _tracks_0. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ dummy_cell ┆ rep1     ┆ ctrl    ┆ subset_1 ┆ … ┆ 3.486127   ┆ 138.048715 ┆ 0.209477  ┆ 0.421677  │
│ _tracks_1. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ dummy_cell ┆ rep1     ┆ ctrl    ┆ subset_1 ┆ … ┆ 2.057925   ┆ 96.18316   ┆ 0.201353  ┆ 0.481521  │
│ _tracks_2. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ dummy_cell ┆ rep2     ┆ ctrl    ┆ subset_1 ┆ … ┆ 3.090928   ┆ 234.175717 ┆ 0.764987  ┆ 0.775168  │
│ _tracks_0. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ dummy_cell ┆ rep2     ┆ ctrl    ┆ subset_1 ┆ … ┆ 2.737676   ┆ 179.283303 ┆ 0.630184  ┆ 0.673595  │
│ _tracks_1. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ …          ┆ …        ┆ …       ┆ …        ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ dummy_cell ┆ rep1     ┆ treated ┆ subset_2 ┆ … ┆ 6.237907   ┆ 183.762928 ┆ 0.299199  ┆ 0.299199  │
│ _tracks_1. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ dummy_cell ┆ rep1     ┆ treated ┆ subset_2 ┆ … ┆ 5.047387   ┆ 202.886479 ┆ 0.171391  ┆ 0.423011  │
│ _tracks_2. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ dummy_cell ┆ rep2     ┆ treated ┆ subset_2 ┆ … ┆ 5.737695   ┆ 285.243526 ┆ 0.414093  ┆ 0.522809  │
│ _tracks_0. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ dummy_cell ┆ rep2     ┆ treated ┆ subset_2 ┆ … ┆ 2.74256    ┆ 198.944863 ┆ 0.703973  ┆ 0.741818  │
│ _tracks_1. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ dummy_cell ┆ rep2     ┆ treated ┆ subset_2 ┆ … ┆ 4.782083   ┆ 335.323802 ┆ 0.725988  ┆ 0.754523  │
│ _tracks_2. ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
│ csv        ┆          ┆         ┆          ┆   ┆            ┆            ┆           ┆           │
└────────────┴──────────┴─────────┴──────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [12]:
# data_object.plot_tracks(fmt='html', smoothing_window=5, color='random', show_ids=True)

In [13]:
# data_object.plot_tracks(color='random', align_start=True, show_ids=True)

In [14]:
timepoints = data_object.compute_timepoints(grouping_level='lowest', bootstrap_ci=True, inferative_error=True, ci_confidence=0.9)

timepoints.to_pandas()

C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin\src\data_compute\data_frames.py:1552: UserWarning: Not enough finite data points to compute confidence interval.
  warn("Not enough finite data points to compute confidence interval.")
c:\Users\modri\miniconda3\envs\peregrin\lib\site-packages\scipy\stats\_resampling.py:147: RuntimeWarning: invalid value encountered in scalar divide
  a_hat = 1/6 * sum(nums) / sum(dens)**(3/2)
c:\Users\modri\miniconda3\envs\peregrin\lib\site-packages\scipy\_lib\_util.py:440: DegenerateDataWarning: The BCa confidence interval cannot be calculated. This problem is known to occur when the distribution is degenerate or the statistic is np.min.
  return fun(*args, **kwargs)

,subgroup,group,subset,set,time_point,frame,cum_track_length_min,cum_track_length_max,cum_track_length_mean,cum_track_length_median,...,instantaneous_speed_mean_ci90_high,cum_mean_straight_line_speed_mean_ci90_low,cum_mean_straight_line_speed_mean_ci90_high,cum_forward_progression_linearity_mean_ci90_low,cum_forward_progression_linearity_mean_ci90_high,cum_sum_directional_change_mean_ci90_low,cum_sum_directional_change_mean_ci90_high,cum_mean_directional_change_mean_ci90_low,cum_mean_directional_change_mean_ci90_high,grouping_level
0,rep1,ctrl,subset_1,set_A,3.0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,subgroup
1,rep1,ctrl,subset_1,set_A,4.0,1,1.629535,8.321949,4.271931,2.864308,...,6.502735,1.020563,3.251368,NaN,NaN,NaN,NaN,NaN,NaN,subgroup
2,rep1,ctrl,subset_1,set_A,5.0,2,3.889163,17.022051,8.736303,5.297696,...,6.611197,1.370423,5.661906,0.580694,0.664032,9.765548,59.055369,9.765548,59.055369,subgroup
3,rep1,ctrl,subset_1,set_A,6.0,3,5.907003,25.192442,13.413622,9.141421,...,6.728169,1.659393,6.102932,0.675065,0.741735,21.125711,85.930383,10.562855,42.965192,subgroup
4,rep1,ctrl,subset_1,set_A,7.0,4,6.942866,35.092584,18.048424,12.109822,...,9.900142,1.659233,5.956597,0.754803,0.792728,24.867690,145.157372,8.289230,48.385791,subgroup
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,rep2,treated,subset_2,set_B,95.0,92,255.825351,524.717422,401.819784,424.916581,...,5.651501,2.140981,3.444876,0.391525,0.750878,1307.178937,2575.675875,14.364604,25.220842,subgroup
1548,rep2,treated,subset_2,set_B,96.0,93,259.541975,531.179931,406.947346,430.120132,...,6.042856,2.117816,3.434223,0.398111,0.738665,1333.970188,2318.691684,12.063364,25.203170,subgroup
1549,rep2,treated,subset_2,set_B,97.0,94,263.265266,535.844811,410.948239,433.734639,...,4.664880,2.100544,3.395160,0.400943,0.729530,1142.956956,2348.133665,14.725167,25.248749,subgroup
1550,rep2,treated,subset_2,set_B,98.0,95,266.812055,541.909709,415.791951,438.654091,...,5.683082,2.085812,3.367956,0.405866,0.720213,1381.792936,2621.344206,14.699925,25.094114,subgroup
1551,rep2,treated,subset_2,set_B,99.0,96,268.185440,545.597949,419.400469,444.418019,...,5.072032,2.073949,3.326209,0.409824,0.711241,1395.256657,2658.791635,12.343761,25.115925,subgroup

In [15]:
timepoints = data_object.compute_timepoints(grouping_level='lowest', bootstrap_ci=True, inferative_error=True)

timepoints.to_pandas()

C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin\src\data_compute\data_frames.py:1552: UserWarning: Not enough finite data points to compute confidence interval.
  warn("Not enough finite data points to compute confidence interval.")
c:\Users\modri\miniconda3\envs\peregrin\lib\site-packages\scipy\stats\_resampling.py:147: RuntimeWarning: invalid value encountered in scalar divide
  a_hat = 1/6 * sum(nums) / sum(dens)**(3/2)
c:\Users\modri\miniconda3\envs\peregrin\lib\site-packages\scipy\_lib\_util.py:440: DegenerateDataWarning: The BCa confidence interval cannot be calculated. This problem is known to occur when the distribution is degenerate or the statistic is np.min.
  return fun(*args, **kwargs)

,subgroup,group,subset,set,time_point,frame,cum_track_length_min,cum_track_length_max,cum_track_length_mean,cum_track_length_median,...,instantaneous_speed_mean_ci95_high,cum_mean_straight_line_speed_mean_ci95_low,cum_mean_straight_line_speed_mean_ci95_high,cum_forward_progression_linearity_mean_ci95_low,cum_forward_progression_linearity_mean_ci95_high,cum_sum_directional_change_mean_ci95_low,cum_sum_directional_change_mean_ci95_high,cum_mean_directional_change_mean_ci95_low,cum_mean_directional_change_mean_ci95_high,grouping_level
0,rep1,ctrl,subset_1,set_A,3.0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,subgroup
1,rep1,ctrl,subset_1,set_A,4.0,1,1.629535,8.321949,4.271931,2.864308,...,8.321949,1.020563,4.160975,NaN,NaN,NaN,NaN,NaN,NaN,subgroup
2,rep1,ctrl,subset_1,set_A,5.0,2,3.889163,17.022051,8.736303,5.297696,...,8.700102,1.370423,5.661906,0.580694,0.664032,9.765548,59.055369,9.765548,59.055369,subgroup
3,rep1,ctrl,subset_1,set_A,6.0,3,5.907003,25.192442,13.413622,9.141421,...,8.170391,1.659393,6.227806,0.675065,0.741735,20.921900,118.128909,10.460950,59.064454,subgroup
4,rep1,ctrl,subset_1,set_A,7.0,4,6.942866,35.092584,18.048424,12.109822,...,9.900142,1.659233,6.959038,0.736333,0.793220,24.867690,145.157372,8.289230,48.385791,subgroup
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,rep2,treated,subset_2,set_B,95.0,92,255.825351,524.717422,401.819784,424.916581,...,5.651501,2.140981,3.444876,0.391525,0.753386,1307.178937,2575.675875,12.019773,28.304130,subgroup
1548,rep2,treated,subset_2,set_B,96.0,93,259.541975,531.179931,406.947346,430.120132,...,6.042856,2.117816,3.434223,0.398111,0.738665,1109.829460,2586.911703,12.063364,25.203170,subgroup
1549,rep2,treated,subset_2,set_B,97.0,94,263.265266,535.844811,410.948239,433.734639,...,4.664880,2.100544,3.395160,0.400943,0.729530,1142.956956,2348.133665,12.289860,25.248749,subgroup
1550,rep2,treated,subset_2,set_B,98.0,95,266.812055,541.909709,415.791951,438.654091,...,5.683082,2.085812,3.367956,0.405866,0.720213,1381.792936,2621.344206,12.295357,25.094114,subgroup
1551,rep2,treated,subset_2,set_B,99.0,96,268.185440,545.597949,419.400469,444.418019,...,5.763928,2.066973,3.326209,0.409824,0.711241,1395.256657,2658.791635,12.343761,25.115925,subgroup

In [16]:
data_object

In [17]:
timelagstab = data_object.compute_timelags(grouping_level=["subset", "set"], bootstrap_ci=True)

timelagstab.to_pandas()

,subset,set,frame_lag,time_lag,MSD,MSD_min,MSD_max,MSD_sd,tracks_contributing,position_pairs_contributing,MSD_ci95_low,MSD_ci95_high,directional_change_mean,directional_change_var,grouping_level
0,subset_1,set_A,1,1.0,17.973682,0.008664,101.667321,17.239372,12,1152,16.955466,18.863453,-0.011809,0.125651,subset
1,subset_1,set_B,1,1.0,37.577134,1.798014,143.197483,23.464611,12,1152,36.182062,38.912327,0.002833,0.168827,subset
2,subset_2,set_A,1,1.0,22.716141,0.828084,134.117884,24.346068,12,1152,21.361579,24.180586,-0.008503,0.124927,subset
3,subset_2,set_B,1,1.0,21.855419,0.816109,93.878506,16.773945,12,1152,20.995963,22.855350,0.009982,0.120594,subset
4,subset_1,set_A,2,2.0,66.969576,3.630542,364.995566,61.009778,12,1140,63.411982,70.370423,-0.022942,0.211950,subset
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,None,set_B,94,94.0,59886.222653,2039.159229,271477.825937,78198.077482,24,72,44514.384162,80053.320007,0.276659,0.792359,set
572,None,set_A,95,95.0,72434.444665,176.229885,402127.703178,106863.835353,24,48,49050.233880,109408.247730,-0.058568,0.787953,set
573,None,set_B,95,95.0,60858.524637,2342.562804,272714.637081,79580.226522,24,48,42258.198271,86112.778211,0.552895,0.668445,set
574,None,set_A,96,96.0,73602.056813,86.225042,404464.354655,109842.801830,24,24,40850.305424,130953.236577,NaN,NaN,set
575,None,set_B,96,96.0,61654.269106,2435.523589,273289.880940,81452.755102,24,24,37406.647630,102972.142419,NaN,NaN,set